travis:
  secure:
    BINSTAR_TOKEN: RKkNvgKkaFZLwf2OT/l+SqqUcJMjXW/1hRuPn5fnhrkB2DqmzMTe4lUxA663w1KCNJzSIXtMfmT9Z8ZK9ZU2Xg2zbKDNPaITyDbmOv9o7mgwC7AB9C/Brty6jLt/O61Dh2qPdsx97tXpehrFr1jIHGvrVK/+ZDP6lfeByhQ4tUjLkf+OfRffu8W82+h43e9ySEQKyQBxRcy0piOUqAhwaHfOG8RCrbRAtP1a3A7Zl7DPmb9bYPSXgacnmoSV4U+sKDgORQcPZS7gl1nu+xYTjoYTAWesXc3DFTHR1t/DN6Ikpjvg+R+KTVvpKZ0OyF2DG5ZwoUY/CH+9B1E8Vfd1dQgYCwEuILBpVIyMVlOXvEvLvud3UYjfju0q5JA305HKX+iZ/FvFck4S2X7bGOwtdemmmWxeAbUVUw7gjn8XF5TvBDnczpYpDUhNnw+hrYZUygRza+RQW28jDAhwB4/vid1SvoRojRmGaqlSOwp64M86WAc2mZxzdd2Z10gE0UP4quIFfKYBZbX14X5LSly8E9SjIRcp3yo+TjMJQNPF+n5igqN6XAZ5RX94TQy1zVBU1OwDEa/EuZHbIqYMtsxoES2wVz8wmqWClGy88iuc97YN0ReX0e4CYbmtzyzZXr71x1hAIWr9dCS6x2UXVusKdRB71fTjPgjwoOP0vJknT88=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
