travis:
  secure:
    BINSTAR_TOKEN: BcPodFkmsR8sFwzEPzPvO1cCRDmaN+l5ZX6YTZnANPJbjnK4VfO3eg2M99zCFKDMfQpLBLhbYj8egMrSBnlULGzG75FJkgeuI5yuolaTYqBqrbmn8+ZTDb70zBoZuUfMgAd8TAgM6kKXvUlm1OfLzuTQQmG+4BMuS5MjhA4Mk0SlVs5rkZAxSSF+zCgIfuf2fp9K0YGybfVxSp9RnmBQAGA5rnra9XfYLhzZ7zJ420a3t07dCUt3JPFLGpQ8tajZQlPt6udSKI3hivMVGgwYzFYMWeNCmP4bLQ8ClJWt9SKNtgwVUTRv2lRuXT6KdNjhHzZClSniBMEnzdz6aVRpn53IwRpuVTQROCsCHZE+AgJ0pdWg+PUaKL2nl+5K9hcBXFo7vIlS5eo9gHEqdveRi2XCpSf0xnf9UKXv+Zi2Dlen5no7CfiYO6/xjOyFgSTvtEEJRx3/TMOCPUVD2QPx7fQRU8pqOz/x5axVYaQ6mNokbQ41H5MC7mDbJxbwkzjf82jNv+Cim6UsoENqUygopS6AFb5uEA05UW8gPN3SPDKMQEVvcQolJMvLTFnuZxZ+UBJi40efjszALLqXereWQCeNEt04D0o+L6ogGnkx3AlZKirnlXKQEx81u02iEom9896+7NSOsxZVbmgiAHMdEMKSVPe8eJMVNQuBet1kQq8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
